// <auto-generated />
using System;
using AirlyAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirlyAnalyzer.Migrations
{
    [DbContext(typeof(AirlyContext))]
    [Migration("20200405205908_ChangeMeasurementsPropertiesTypes")]
    partial class ChangeMeasurementsPropertiesTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            modelBuilder.Entity("AirlyAnalyzer.Models.AirQualityForecast", b =>
                {
                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallationId")
                        .HasColumnType("int");

                    b.Property<byte>("AirlyCaqi")
                        .HasColumnType("tinyint");

                    b.Property<int>("Pm10")
                        .HasColumnType("int");

                    b.Property<int>("Pm25")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TillDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FromDateTime", "InstallationId");

                    b.ToTable("ArchiveForecasts");
                });

            modelBuilder.Entity("AirlyAnalyzer.Models.AirQualityForecastAccuracy", b =>
                {
                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallationId")
                        .HasColumnType("int");

                    b.Property<byte>("AirlyCaqiError")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ForecastRequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pm10Error")
                        .HasColumnType("int");

                    b.Property<int>("Pm25Error")
                        .HasColumnType("int");

                    b.Property<DateTime>("TillDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FromDateTime", "InstallationId");

                    b.ToTable("ForecastAccuracyRates");
                });

            modelBuilder.Entity("AirlyAnalyzer.Models.AirQualityMeasurement", b =>
                {
                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallationId")
                        .HasColumnType("int");

                    b.Property<byte>("AirlyCaqi")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Humidity")
                        .HasColumnType("tinyint");

                    b.Property<int>("Pm1")
                        .HasColumnType("int");

                    b.Property<int>("Pm10")
                        .HasColumnType("int");

                    b.Property<int>("Pm25")
                        .HasColumnType("int");

                    b.Property<int>("Pressure")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Temperature")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TillDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FromDateTime", "InstallationId");

                    b.ToTable("ArchiveMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
